"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports["default"] = void 0;

var _CSSFactory = _interopRequireDefault(require("../CSSFactory"));

var _Generator = _interopRequireDefault(require("../Generator"));

var _VueFactory = _interopRequireDefault(require("./VueFactory"));

var _VueMultiPageWriter = _interopRequireDefault(require("./VueMultiPageWriter"));

var _RouterFactory = _interopRequireDefault(require("./RouterFactory"));

var ExportUtil = _interopRequireWildcard(require("../ExportUtil"));

function _interopRequireWildcard(obj) { if (obj && obj.__esModule) { return obj; } else { var newObj = {}; if (obj != null) { for (var key in obj) { if (Object.prototype.hasOwnProperty.call(obj, key)) { var desc = Object.defineProperty && Object.getOwnPropertyDescriptor ? Object.getOwnPropertyDescriptor(obj, key) : {}; if (desc.get || desc.set) { Object.defineProperty(newObj, key, desc); } else { newObj[key] = obj[key]; } } } } newObj["default"] = obj; return newObj; } }

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { "default": obj }; }

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

function _defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } }

function _createClass(Constructor, protoProps, staticProps) { if (protoProps) _defineProperties(Constructor.prototype, protoProps); if (staticProps) _defineProperties(Constructor, staticProps); return Constructor; }

var VueGenerator =
/*#__PURE__*/
function () {
  function VueGenerator() {
    _classCallCheck(this, VueGenerator);
  }

  _createClass(VueGenerator, [{
    key: "run",
    value: function run(app, conf) {
      var generator = new _Generator["default"](new _VueFactory["default"](conf), new _CSSFactory["default"](conf.css.grid, conf.css.prefix, true));
      var result = generator.run(app, conf.css.grid);
      var writer = new _VueMultiPageWriter["default"]();
      var files = writer.getFiles(result, conf);
      files = files.concat(ExportUtil.getImages(app));

      if (conf.vue && conf.vue.generateRouter === true) {
        files = new _RouterFactory["default"]().run(files, conf, app);
      }

      if (conf.vue && conf.vue.generateApp === true) {
        files.push(this.getAppVue(app));
      }

      return files;
    }
  }, {
    key: "getAppVue",
    value: function getAppVue(app) {
      var content = "\n<template>\n  <!-- Generated by Quant-UX -->\n  <div id=\"app\">\n    <router-view/>\n  </div>\n</template>\n\n<style>\n#app {\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n  min-height: 100%\n}\n</style>\n";
      return {
        name: 'App.vue',
        type: 'vueApp',
        content: content
      };
    }
  }]);

  return VueGenerator;
}();

exports["default"] = VueGenerator;