import CSSFactory from '../CSSFactory'
import Generator from '../Generator'
import VueFactory from './VueFactory'
import VueMultiPageWriter from './VueMultiPageWriter'
import RouterFactory from './RouterFactory'
import * as ExportUtil from '../ExportUtil'

export default class VueGenerator {

  run(app, conf) {
    let generator = new Generator(
        new VueFactory(conf), 
        new CSSFactory(conf.css.grid, conf.css.prefix, true)
    )
    let result = generator.run(app, conf.css.grid)
    let writer = new VueMultiPageWriter()
    let files = writer.getFiles(result, conf)
    files = files.concat(ExportUtil.getImages(app))
    if (conf.vue && conf.vue.generateRouter === true) {
      files = new RouterFactory().run(files, conf, app)
    }
    if (conf.vue && conf.vue.generateApp === true) {
      files.push(this.getAppVue(app))
    }
    return files
  }

  getAppVue (app) {
    let content = `
<template>
  <!-- Generated by Quant-UX -->
  <div id="app">
    <router-view/>
  </div>
</template>

<style>
#app {
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  min-height: 100%
}
</style>
`
    return {            
      name: 'App.vue',
      type: 'vueApp',
      content: content     
    }       
  }
}